const areaToZone = {

  // ===========================
  // MADHURAWADA ZONE
  // ===========================
  "madhurawada": "Madhurawada",
  "kommadi": "Madhurawada",
  "pm palem": "Madhurawada",
  "car shed": "Madhurawada",
  "endada": "Madhurawada",
  "yendada": "Madhurawada",
  "sagar nagar": "Madhurawada",
  "rushikonda": "Madhurawada",
  "rushikonda beach": "Madhurawada",
  "mangamaripeta": "Madhurawada",
  "kapuluppada": "Madhurawada",
  "gudlavanipalem": "Madhurawada",
  "paradesipalem": "Madhurawada",
  "lawsons bay": "Madhurawada",
  "gitam": "Madhurawada",
  "gitam university": "Madhurawada",
  "gayatri vidya parishad": "Madhurawada",
  "bakkannapalem": "Madhurawada",
  "srinivasa nagar": "Madhurawada",
  "vuda colony": "Madhurawada",

  // EAST ZONE
  "mvp colony": "East",
  "isukathota": "East",
  "shivajipalem": "East",
  "venkojipalem": "East",
  "hb colony": "East",
  "pedda waltair": "East",
  "maddilapalem": "East",
  "seethammadhara": "East",
  "asilmetta": "East",
  "siripuram": "East",
  "cbm compound": "East",
  "dwaraka nagar": "East",
  "ramnagar": "East",
  "akkayyapalem": "East",
  "lalitha nagar": "East",
  "railway new colony": "East",
  "maharanipeta": "East",
  "beach road": "East",
  "pandurangapuram": "East",
  "kirlampudi layout": "East",

  // NORTH ZONE
  "old post office": "North",
  "poorna market": "North",
  "jagadamba": "North",
  "town kotha road": "North",
  "one town": "North",
  "chengal rao peta": "North",
  "allipuram": "North",
  "daba gardens": "North",
  "port area": "North",
  "naval dockyard": "North",
  "malkapuram": "North",
  "kancherapalem": "North",
  "kancharapalem": "North",
  "burma camp": "North",
  "saligramapuram": "North",
  "sriharipuram": "North",
  "gnanapuram": "North",

  // SOUTH ZONE
  "kurmannapalem": "South",
  "aganampudi": "South",
  "steel plant": "South",
  "ukkunagaram": "South",
  "parawada": "South",
  "atchutapuram": "South",
  "duvvada": "South",
  "pedagantyada": "South",
  "auto nagar": "South",
  "scindia": "South",
  "harbour": "South",

  // GAJUWAKA ZONE
  "gajuwaka": "Gajuwaka",
  "new gajuwaka": "Gajuwaka",
  "old gajuwaka": "Gajuwaka",
  "sheela nagar": "Gajuwaka",
  "nad junction": "Gajuwaka",
  "airport": "Gajuwaka",
  "bhpv": "Gajuwaka",
  "mindi": "Gajuwaka",
  "vadlapudi": "Gajuwaka",
  "tunglam": "Gajuwaka",
  "lankelapalem": "Gajuwaka",
  "simhachalam": "Gajuwaka",

  // PENDURTHI ZONE
  "pendurthi": "Pendurthi",
  "sujatha nagar": "Pendurthi",
  "chinamushidiwada": "Pendurthi",
  "purushottapuram": "Pendurthi",
  "kothavalasa road": "Pendurthi",
  "pulaganipalem": "Pendurthi",
  "sabbavaram": "Pendurthi",
  "anandapuram": "Pendurthi",
  "tagarapuvalasa": "Pendurthi",
  "bakkannapalem junction": "Pendurthi",
  "naiduthota": "Pendurthi",
  "naidu thota": "Pendurthi",
  "sai madhava nagar": "Pendurthi",
  "vepagunta": "Pendurthi",
  "sanathivanipalem": "Pendurthi",
  "sai durga nagar": "Pendurthi",

  // BHEEMUNIPATNAM ZONE
  "bheemunipatnam": "Bheemunipatnam",
  "bheemili": "Bheemunipatnam",
  "thimmapuram": "Bheemunipatnam",
  "dakamarri": "Bheemunipatnam",
  "majjivalasa": "Bheemunipatnam",
  "nerellavalasa": "Bheemunipatnam",
  "kothavalasa beach": "Bheemunipatnam",
  "polipalli": "Bheemunipatnam",
  "chippada": "Bheemunipatnam",
  "tallavalasa": "Bheemunipatnam",
  // --- widened matching: additional localities confirmed under Madhurawada (official GVMC ward data) ---
  "amrutha arcade": "Madhurawada",
  "ayodhya nagar": "Madhurawada",
  "ayyappa nagar": "Madhurawada",
  "bapujinagar": "Madhurawada",
  "bhagavandas colony": "Madhurawada",
  "bhuvaneswari colony": "Madhurawada",
  "boravanipalem": "Madhurawada",
  "bottavanipalem": "Madhurawada",
  "boyyipalem junction": "Madhurawada",
  "car shed junction": "Madhurawada",
  "carpenter colony": "Madhurawada",
  "chandram palem village": "Madhurawada",
  "chandrampalem": "Madhurawada",
  "chanukyapuri layout": "Madhurawada",
  "chepaluppada panchayat": "Madhurawada",
  "chinagantyada": "Madhurawada",
  "chinna rushikonda": "Madhurawada",
  "devimetta": "Madhurawada",
  "dhobi colony": "Madhurawada",
  "dockyard colony": "Madhurawada",
  "ews colony": "Madhurawada",
  "fci layout": "Madhurawada",
  "ganeshnagar road": "Madhurawada",
  "gayatri nagar": "Madhurawada",
  "gcc layout": "Madhurawada",
  "gollala yendada": "Madhurawada",
  "jk layout": "Madhurawada",
  "jv agraharam panchayat": "Madhurawada",
  "k nagarpalem panchayat": "Madhurawada",
  "kalanagar": "Madhurawada",
  "kapuluppada panchayat": "Madhurawada",
  "kommadi junction": "Madhurawada",
  "kommadi sc colony": "Madhurawada",
  "kommadi village": "Madhurawada",
  "law college": "Madhurawada",
  "laxmivanipalem": "Madhurawada",
  "madhurawada jn": "Madhurawada",
  "madhurawada junction": "Madhurawada",
  "mallayyapalem": "Madhurawada",
  "marikavalasa hill": "Madhurawada",
  "mithilapuri vuda colony": "Madhurawada",
  "musalayyapalem": "Madhurawada",
  "nagarampalem village": "Madhurawada",
  "ngo's layout": "Madhurawada",
  "nidigattu panchayat": "Madhurawada",
  "ntr colony": "Madhurawada",
  "old madhurawada": "Madhurawada",
  "old pm palem": "Madhurawada",
  "paradesi palem": "Madhurawada",
  "peda rushikonda": "Madhurawada",
  "pkpalem": "Madhurawada",
  "port colony": "Madhurawada",
  "prasanthi nagar": "Madhurawada",
  "priyadarsini colony": "Madhurawada",
  "rajeev gruha kalpa": "Madhurawada",
  "ramaraju enclave": "Madhurawada",
  "rtc colony": "Madhurawada",
  "sadguru sai colony": "Madhurawada",
  "sagarnagar": "Madhurawada",
  "sai priya garden": "Madhurawada",
  "sai ram colony": "Madhurawada",
  "sandeepini nagar": "Madhurawada",
  "shyam nagar": "Madhurawada",
  "siddardha nagar": "Madhurawada",
  "sirigudi nagar": "Madhurawada",
  "siva shakti nagar": "Madhurawada",
  "skml layout": "Madhurawada",
  "sri laxmi nagar": "Madhurawada",
  "subhash nagar": "Madhurawada",
  "subregistrar area": "Madhurawada",
  "sundarnagar": "Madhurawada",
  "swarna bharathi nagar": "Madhurawada",
  "swatantra nagar": "Madhurawada",
  "swayamkrushi nagar": "Madhurawada",
  "tailors colony": "Madhurawada",
  "tarakaramanagar": "Madhurawada",
  "thatichetlapalem": "Madhurawada",
  "timmapuram": "Madhurawada",
  "usmania colony": "Madhurawada",
  "vambay colony": "Madhurawada",
  "varahagiri nagar": "Madhurawada",
  "vasantha vihar": "Madhurawada",
  "vikalangula colony": "Madhurawada",
  "vivekananda colony": "Madhurawada",
  "yendada main village": "Madhurawada",
  // --- widened matching: additional localities confirmed under East (official GVMC ward data) ---
  "aadarsh nagar": "East",
  "aadarsha nagar": "East",
  "adarshnagar": "East",
  "akkayapalem": "East",
  "akkayapalem road": "East",
  "amar nagar": "East",
  "ambedkar nagar": "East",
  "ambedkar new colony": "East",
  "anna nagar": "East",
  "anthony nagar": "East",
  "apsara colony": "East",
  "arilova sectori": "East",
  "assam gardens": "East",
  "b s layout": "East",
  "balajinagar": "East",
  "bc colony": "East",
  "bhagatsingh nagar": "East",
  "bhanunagar": "East",
  "bharat nagar": "East",
  "bs layout": "East",
  "btr nagar": "East",
  "cancer hospital area": "East",
  "central prison": "East",
  "central prison area": "East",
  "chaitanya nagar": "East",
  "chakali gedda": "East",
  "chakalipeta": "East",
  "chalapti nagar": "East",
  "chinagadili": "East",
  "chinawaltair": "East",
  "chinnuru": "East",
  "commissioner bunglow area": "East",
  "dairy farm": "East",
  "dandu bazar": "East",
  "dayal nagar": "East",
  "doctors colony": "East",
  "dondaparthi": "East",
  "durga bazar": "East",
  "durganagar": "East",
  "east point colony": "East",
  "eenadu main road": "East",
  "fish market road": "East",
  "fishermen colony": "East",
  "golla veedhi": "East",
  "hbcolony": "East",
  "housing board office area": "East",
  "indira nagar": "East",
  "isukathota village": "East",
  "j r nagar": "East",
  "jai bheem nagar": "East",
  "jodugullapalem": "East",
  "kailasapuram road": "East",
  "kailashagiri": "East",
  "kalabharathi": "East",
  "kanakala dibba": "East",
  "kannayyapeta": "East",
  "kasturi nagar": "East",
  "kgh opp": "East",
  "kirlampudi lay out": "East",
  "kotha venkojipalem": "East",
  "kotta jalaripeta": "East",
  "krm colony": "East",
  "lakshmi nagar": "East",
  "lakshmi narasimha nagar": "East",
  "laxmi nagar": "East",
  "lic qtrs": "East",
  "maddilapalem main road": "East",
  "madhura nagar": "East",
  "madhusudhan nagar": "East",
  "mayuri nagar": "East",
  "mustapha colony": "East",
  "muvvalavanipalem": "East",
  "mvp sector 2": "East",
  "mvp sector 9 & 10": "East",
  "nakkavanipalem": "East",
  "nandagirinagar": "East",
  "narendra nagar": "East",
  "nauka nagar": "East",
  "near nri hospital": "East",
  "nggo's colony": "East",
  "nmr colony": "East",
  "old employment office": "East",
  "old resapuvanipalem": "East",
  "old venkojipalem": "East",
  "operation colony": "East",
  "p&t colony": "East",
  "pandurangapuram area": "East",
  "parvathi nagar": "East",
  "peawaltari junction": "East",
  "pedawaltair": "East",
  "pedawaltair village": "East",
  "peethalavanipalem": "East",
  "peethapuram colony": "East",
  "pineapple colony": "East",
  "police quarters": "East",
  "prakasarao peta": "East",
  "prakasha rao peta": "East",
  "prasantha nagar": "East",
  "priyadarshini colony": "East",
  "priyadarshini nagar": "East",
  "rajendra nagar": "East",
  "rajiv nagar": "East",
  "ramajogi peta": "East",
  "ramalayam street": "East",
  "ramatalkies road": "East",
  "raveendra nagar": "East",
  "ravindra nagar": "East",
  "resapuvanipalem": "East",
  "sai baba temple area": "East",
  "sai nagar": "East",
  "salipeta": "East",
  "samatha college area": "East",
  "sanjay nagar": "East",
  "sanjeev nagar colony": "East",
  "santhi nagar": "East",
  "sbi colony": "East",
  "sc & st colony": "East",
  "sector1 mvp colony": "East",
  "sector5 mvp colony": "East",
  "sector8 mvp colony": "East",
  "seethammadhara junction": "East",
  "seethammpeta": "East",
  "shantipuram": "East",
  "shramika nagar": "East",
  "sig nagar": "East",
  "simhadripuram": "East",
  "siva sankar nagar": "East",
  "sivaganesh nagar": "East",
  "sivaji nagar": "East",
  "sivajipalem": "East",
  "sivajipark area": "East",
  "skml nagar": "East",
  "south jail road": "East",
  "srihari nagar": "East",
  "srikrishna puram": "East",
  "srinagar": "East",
  "srirangapuram": "East",
  "state bank area": "East",
  "state bank colony": "East",
  "sundar nagar": "East",
  "sundarayya nagar": "East",
  "surya teja nagar": "East",
  "suryabagh": "East",
  "thotagaruvu": "East",
  "tpt colony": "East",
  "tulasipeta": "East",
  "uma nagar": "East",
  "vasavanipalem": "East",
  "verni durga nagar": "East",
  "vidyuthnagar": "East",
  "vijayanagar palace layout": "East",
  "vinayaka nagar": "East",
  "vip road": "East",
  "visakha eye hospital area": "East",
  "visalakshi nagar": "East",
  "vishnupuri colony": "East",
  "vizayanagar colony": "East",
  "vuda apts": "East",
  "vuda quarters": "East",
  "yellammathota": "East",
  // --- widened matching: additional localities confirmed under North (official GVMC ward data) ---
  "ajantha colony": "North",
  "akc colony": "North",
  "amzeri park": "North",
  "bhanoji nagar": "North",
  "bhupesh nagar": "North",
  "chagantivari street": "North",
  "chengalaraopeta": "North",
  "chilakapeta": "North",
  "childrens convent area": "North",
  "circuit house": "North",
  "daspalla hills": "North",
  "dolphin hills": "North",
  "esi hospital quarters": "North",
  "gollaveedhi": "North",
  "grandhalayam veedhi": "North",
  "jaganadhapuram": "North",
  "kailasametta": "North",
  "konda area": "North",
  "malakapuram": "North",
  "mulagada": "North",
  "naval park": "North",
  "netaji nagar": "North",
  "opp post hospital": "North",
  "padma nagar": "North",
  "paindorapeta": "North",
  "pitandibba": "North",
  "potti sriramulu park": "North",
  "pr gardens": "North",
  "prasad gardens": "North",
  "railway grounds": "North",
  "rama krishna nagar": "North",
  "ramalayam": "North",
  "ramalayam temple area": "North",
  "rangireeju veedhi": "North",
  "relli veedhi": "North",
  "sabbivanipeta": "North",
  "sangivalasa": "North",
  "sangivalasa colony": "North",
  "santha road": "North",
  "satyanarayana peta market road": "North",
  "seva nagar": "North",
  "shipyard colony": "North",
  "stadium road": "North",
  "taraka rama colony": "North",
  "taraka rama nagar": "North",
  "thagrapuvalasa main road": "North",
  "town main road": "North",
  "vuda complex": "North",
  // --- widened matching: additional localities confirmed under South (official GVMC ward data) ---
  "ayyannapalem": "South",
  "bapuji colony": "South",
  "bhanojithota": "South",
  "butchayyapeta": "South",
  "china tadi": "South",
  "chinthala lova": "South",
  "double tank": "South",
  "gandhigram": "South",
  "gnt road": "South",
  "islam peta": "South",
  "kakarlova": "South",
  "kalinga nagar": "South",
  "kanithi colony": "South",
  "kanitinaidu colony": "South",
  "madhavadhara": "South",
  "narasimha nagar": "South",
  "naval quarters yarada": "South",
  "nellimukku": "South",
  "netaji colony": "South",
  "new dibbapalem": "South",
  "pedakorada": "South",
  "pedhagantyada": "South",
  "pithapuram colony": "South",
  "pittavanipalem": "South",
  "port quarters": "South",
  "sai ram nagar": "South",
  "sanjeevagiricolony": "South",
  "satavahana nagar": "South",
  "satyanarayanapuram": "South",
  "seetharam nagaram": "South",
  "siddeswaram": "South",
  "simhagiri colony": "South",
  "singaraya metta": "South",
  "steel plant sector1&ii": "South",
  "steel plant sectors 3 to 11": "South",
  "sundarayya colony": "South",
  "tenneti nagar": "South",
  "tgr nagar": "South",
  "varahagiri colony": "South",
  "vidya nagar": "South",
  "vikas nagar": "South",
  "vuda phases": "South",
  "yarada": "South",
  // --- widened matching: additional localities confirmed under Gajuwaka (official GVMC ward data) ---
  "adivivaram": "Gajuwaka",
  "akkireddy palem": "Gajuwaka",
  "azeemabad": "Gajuwaka",
  "bc road": "Gajuwaka",
  "bhpv township": "Gajuwaka",
  "chittinaidu colony": "Gajuwaka",
  "durga puram": "Gajuwaka",
  "gowri nagar": "Gajuwaka",
  "indira colony": "Gajuwaka",
  "kailash nagar": "Gajuwaka",
  "lbs nagar": "Gajuwaka",
  "marripalem vuda layout": "Gajuwaka",
  "maruthi nagar": "Gajuwaka",
  "panchavati": "Gajuwaka",
  "simhachalam hill": "Gajuwaka",
  // --- widened matching: additional localities confirmed under Pendurthi (official GVMC ward data) ---
  "104 area": "Pendurthi",
  "adarsha nagar": "Pendurthi",
  "butchirajupalem": "Pendurthi",
  "chandra nagar": "Pendurthi",
  "chinnamusidiwada": "Pendurthi",
  "gopalapatnam": "Pendurthi",
  "kothapalem": "Pendurthi",
  "mondibanda": "Pendurthi",
  "nalla quary": "Pendurthi",
  "narava": "Pendurthi",
  "old gopalapatnam": "Pendurthi",
  "pendurthi old village": "Pendurthi",
  "purushothapuram": "Pendurthi",
  "rr venkatapuram": "Pendurthi",
  // --- widened matching: additional localities confirmed under Bheemunipatnam (official GVMC ward data) ---
  "alankavariveedhi": "Bheemunipatnam",
  "bogguroad": "Bheemunipatnam",
  "bunglow metta": "Bheemunipatnam",
  "chakalipetaharizanapeta": "Bheemunipatnam",
  "chinthalapudi apparao street": "Bheemunipatnam",
  "cj mill kalyana mandapam": "Bheemunipatnam",
  "cjmill factory school area": "Bheemunipatnam",
  "harizana peta": "Bheemunipatnam",
  "jogavari veedhi": "Bheemunipatnam",
  "kapuveedhi": "Bheemunipatnam",
  "kondapeta": "Bheemunipatnam",
  "kondapeta colony": "Bheemunipatnam",
  "kothapeta vani school area": "Bheemunipatnam",
  "kuncham apprao street": "Bheemunipatnam",
  "local office road": "Bheemunipatnam",
  "mangalaveedhi": "Bheemunipatnam",
  "medharavedhi": "Bheemunipatnam",
  "nagarapuveedhi": "Bheemunipatnam",
  "nerella valasa colony": "Bheemunipatnam",
  "nerellavalasa hill area": "Bheemunipatnam",
  "parimi thammayya lane": "Bheemunipatnam",
  "rajaveedhi": "Bheemunipatnam",
  "ramannapeta": "Bheemunipatnam",
  "ramaveedhi": "Bheemunipatnam",
  "reddika veedhi": "Bheemunipatnam",
  "relli vedhi": "Bheemunipatnam",
  "sapthagiri theatre area": "Bheemunipatnam",
  "telephone exchange area": "Bheemunipatnam",
  "thata theatre area": "Bheemunipatnam",
  "thippana vari veedhi": "Bheemunipatnam",
  "thotaveedhi": "Bheemunipatnam",
  "velam peta": "Bheemunipatnam",
  "vempadavariveedhi": "Bheemunipatnam",
  "venkateswara metta": "Bheemunipatnam",
  "wilson peta company quarters": "Bheemunipatnam",
  "wilsonpeta": "Bheemunipatnam",
};

module.exports = areaToZone;